# Generated by Django 3.0.4 on 2020-03-09 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description_content', models.TextField(blank=True, null=True)),
                ('description_mediatype', models.CharField(default='plain/text', max_length=127)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('mail', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=230, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('global_plus_code', models.CharField(blank=True, max_length=230, null=True)),
                ('tags', models.ManyToManyField(to='calagari.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('info', models.TextField(blank=True, null=True)),
                ('allow_create_events', models.BooleanField(default=True)),
                ('allow_create_venues', models.BooleanField(default=False)),
                ('allow_create_tags', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('is_draft', models.BooleanField(default=True)),
                ('description_content', models.TextField(blank=True, null=True)),
                ('description_mediatype', models.CharField(default='plain/text', max_length=127)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('mail', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=250, null=True)),
                ('booking_enabled', models.BooleanField(default=True)),
                ('booking_per_day', models.BooleanField(default=False)),
                ('booking_time_slot', models.BooleanField(default=False)),
                ('booking_automatic_accepted', models.BooleanField(default=False)),
                ('booking_info', models.TextField(blank=True, null=True)),
                ('spots', models.IntegerField(null=True)),
                ('start_booking', models.DateTimeField(blank=True, null=True)),
                ('end_booking', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calagari.Venue')),
                ('tags', models.ManyToManyField(to='calagari.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('booking_info', models.TextField(blank=True, null=True)),
                ('spots', models.IntegerField(null=True)),
                ('start_booking', models.DateTimeField(blank=True, null=True)),
                ('end_booking', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calagari.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=None, null=True)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calagari.Day')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calagari.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'day', 'user')},
            },
        ),
    ]
